# Generated by Django 5.1.4 on 2024-12-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='photos/products', verbose_name='Фото товара'),
        ),
    ]
