# Generated by Django 5.1.4 on 2024-12-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_options_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Склад тканини'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вид тканини'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=32, max_length=255, verbose_name='Модель'),
            preserve_default=False,
        ),
    ]
