# Generated by Django 5.1.4 on 2024-12-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_color_product_fabric_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=500, verbose_name='Назва товару'),
        ),
    ]
