# Generated by Django 5.1.4 on 2025-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Додаткові зображення'),
        ),
    ]
