# Generated by Django 5.1.4 on 2024-12-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_slider_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайди'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS клас'),
        ),
    ]
