# Generated by Django 5.1.4 on 2024-12-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплату', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
